### ISSUE TITLE
Gem doesnt work with postgreSQL

### ISSUE THREAD

**Issue by denniscastro** [brunofrank/class-table-inheritance#6]
The gem works fine in mysql adapter but if you read the log, it shows some warnings
These warnings dont pass in postgreSQL adapter and it rollbacks the transactions
You can create a record
@book = Book.new
@Book.name="Book 1"
@book.save
until now all works fine in postgress and mysql (both with warnings)
But if you update the book
@book = Book.find(1)
@Book.name = "Book 1"
@Book.pages = 50
@book.save
you get:
PGError: ERROR:  current transaction is aborted, commands ignored until end of transaction block

If you desabled auto ROLLBACK from the postgres server works fine..
But not if you use Heroku for example.

Dennis C.

**Comment by donv** [comment]
I am using this gem with Postgresql, so I think we can call this fixed.
